# Generated by Django 4.1 on 2022-08-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookfiller",
            name="description",
        ),
        migrations.AddField(
            model_name="bookfiller",
            name="side",
            field=models.CharField(default="nil", max_length=5),
        ),
    ]
