# Generated by Django 4.1 on 2022-08-22 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_remove_bookfiller_description_bookfiller_side"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookfiller",
            old_name="trade_amount",
            new_name="user_ref_price",
        ),
    ]
