# Generated by Django 4.1 on 2022-08-09 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_rename_exchenge_exchange"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="marketmakerbot",
            name="trade_qty_range_high",
        ),
        migrations.RemoveField(
            model_name="marketmakerbot",
            name="trade_qty_range_low",
        ),
        migrations.AddField(
            model_name="marketmakerbot",
            name="side",
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name="marketmakerbot",
            name="user_ref_price",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="marketmakerbot",
            name="pair_token",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="dashboard.botconfigpairtokens",
                verbose_name="Token pair",
            ),
        ),
    ]
