# Generated by Django 4.0.6 on 2022-07-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_marketmakerbotorderhistory_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketmakerbotorderhistory',
            name='pair_token',
            field=models.CharField(default='DUMMY_TK', max_length=16),
        ),
        migrations.AddField(
            model_name='marketmakerbotorderhistory',
            name='spreed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marketmakerbotorderhistory',
            name='status',
            field=models.CharField(default='NONE', max_length=16),
        ),
    ]
