# Generated by Django 4.0.6 on 2022-07-27 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_marketmakerbotorderhistory_pair_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair_token', models.CharField(default='DUMMY_TK', max_length=16)),
                ('order_size', models.IntegerField(default=0)),
                ('number_of_orders', models.IntegerField(default=0)),
                ('budget', models.FloatField(default=0)),
                ('trade_amount', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'market_maker_bid_bot',
            },
        ),
        migrations.CreateModel(
            name='CancelOrderBookBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_order_id', models.CharField(max_length=64)),
                ('order_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.marketmakerbot')),
            ],
            options={
                'db_table': 'cancel_order_book_mm_bot',
            },
        ),
        migrations.CreateModel(
            name='CancelOrderBookBID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_order_list', models.CharField(max_length=2046)),
                ('order_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bid_bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.bidbot')),
            ],
            options={
                'db_table': 'cancel_order_book_bid_bot',
            },
        ),
        migrations.CreateModel(
            name='BidBotOrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair_token', models.CharField(default='DUMMY_TK', max_length=16)),
                ('order_size', models.IntegerField(default=0)),
                ('number_of_orders', models.IntegerField(default=0)),
                ('budget', models.FloatField(default=0)),
                ('trade_amount', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bid_bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.bidbot')),
            ],
            options={
                'db_table': 'bid_bot_order_history',
            },
        ),
    ]
