# Generated by Django 4.1 on 2022-08-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_marketmakerbotautotradequeue"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketmakerbotautotradequeue",
            name="candle",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="marketmakerbotautotradequeue",
            name="quantity",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="marketmakerbotautotradequeue",
            name="side",
            field=models.CharField(default="FILL"),
        ),
        migrations.AlterModelTable(
            name="marketmakerbotautotradequeue",
            table="dashboard_marketmakerbotautotradequeue",
        ),
    ]
