# Generated by Django 4.0.6 on 2022-07-27 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_bidbot_cancelorderbookbot_cancelorderbookbid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidbot',
            name='api_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.apikeys'),
        ),
        migrations.AddField(
            model_name='bidbot',
            name='description',
            field=models.CharField(default='None', max_length=256),
        ),
        migrations.AddField(
            model_name='bidbot',
            name='name',
            field=models.CharField(default='None', max_length=32),
        ),
        migrations.AddField(
            model_name='bidbot',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bidbot',
            name='pair_token',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.botconfigpairtokens', verbose_name='Token pair'),
        ),
    ]
