# Generated by Django 4.1 on 2022-08-19 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_marketmakerbotautotradequeue_candle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bidbot",
            name="description",
            field=models.CharField(default="nil", max_length=256),
        ),
        migrations.AlterField(
            model_name="bidbot",
            name="name",
            field=models.CharField(default="nil", max_length=32),
        ),
        migrations.AlterField(
            model_name="bidbotorderhistory",
            name="bid_bot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dashboard.bidbot"
            ),
        ),
        migrations.AlterField(
            model_name="cancelorderbookbid",
            name="bid_bot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dashboard.bidbot"
            ),
        ),
        migrations.AlterField(
            model_name="cancelorderbookbot",
            name="bot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="dashboard.marketmakerbot",
            ),
        ),
        migrations.AlterField(
            model_name="marketmakerbotautotradequeue",
            name="bot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="dashboard.marketmakerbot",
            ),
        ),
        migrations.AlterField(
            model_name="marketmakerbotautotradequeue",
            name="side",
            field=models.CharField(default="FILL", max_length=64),
        ),
        migrations.AlterField(
            model_name="marketmakerbotautotradequeue",
            name="status",
            field=models.CharField(default="FINISHED", max_length=64),
        ),
        migrations.AlterField(
            model_name="marketmakerbotorderhistory",
            name="bot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="dashboard.marketmakerbot",
            ),
        ),
    ]
