# Generated by Django 4.0.6 on 2022-07-27 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_bidbot_api_key_bidbot_description_bidbot_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidbot',
            name='status',
            field=models.CharField(default='NONE', max_length=16),
        ),
        migrations.AddField(
            model_name='marketmakerbot',
            name='status',
            field=models.CharField(default='NONE', max_length=16),
        ),
        migrations.AlterField(
            model_name='bidbot',
            name='api_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.apikeys'),
        ),
        migrations.AlterField(
            model_name='bidbot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
