# Generated by Django 4.0.7 on 2022-09-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geneses', '0002_genesesqueue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genesesqueue',
            old_name='geneses_id',
            new_name='geneses',
        ),
    ]
