# Generated by Django 4.0.7 on 2022-11-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geneses", "0003_rename_geneses_id_genesesqueue_geneses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geneses",
            name="status",
            field=models.CharField(default="STOP", max_length=64),
        ),
    ]
