# Generated by Django 4.1 on 2022-08-29 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookfiller", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookfiller",
            name="pair_token",
            field=models.CharField(default="DUMMy", max_length=64),
        ),
        migrations.AlterField(
            model_name="cancelorderbookbot",
            name="bot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="bookfiller.bookfiller",
            ),
        ),
    ]
