# Generated by Django 4.1 on 2022-08-25 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exchange", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketMakerBot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("description", models.CharField(max_length=256)),
                ("pair_token", models.CharField(default="DUMMY", max_length=16)),
                ("user_ref_price", models.FloatField(default=0)),
                ("side", models.IntegerField(default=0)),
                ("trade_candle", models.IntegerField(default=0)),
                ("trade_amount", models.FloatField(default=0)),
                ("status", models.CharField(default="STOP", max_length=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="exchange.apikeys",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarketMakerBotOrderHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pair_token", models.CharField(default="DUMMY_TK", max_length=16)),
                ("spreed", models.IntegerField(default=0)),
                ("status", models.CharField(default="STOP", max_length=8)),
                ("side", models.CharField(default="Nil", max_length=4)),
                ("trade_qty_low", models.IntegerField(default=0)),
                ("trade_qty_high", models.IntegerField(default=0)),
                ("trade_candle", models.IntegerField(default=0)),
                ("trade_amount", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="autotrade.marketmakerbot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarketMakerBotAutoTradeQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField(default=0)),
                ("quantity", models.FloatField(default=0)),
                ("side", models.CharField(default="FILL", max_length=64)),
                ("status", models.CharField(default="FINISHED", max_length=64)),
                ("candle", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="autotrade.marketmakerbot",
                    ),
                ),
            ],
        ),
    ]
