# Generated by Django 4.0.7 on 2022-11-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotrade', '0003_remove_marketmakerbotorderhistory_spreed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketmakerbot',
            name='photo',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
