# Generated by Django 4.0.7 on 2022-09-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotrade', '0003_remove_marketmakerbotorderhistory_spreed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketmakerbotautotradequeue',
            name='exec_ref_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='marketmakerbotorderhistory',
            name='type',
            field=models.CharField(default='ex_fail', max_length=128),
        ),
    ]
