# Generated by Django 4.0.7 on 2022-11-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotrade', '0004_marketmakerbot_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketmakerbot',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
